name: iboss_assessment
description: "Vault - secure session and encrypted storage demo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.7.0

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5

  # Crypto: AES-256-GCM + PBKDF2-HMAC-SHA256
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
